INSERT INTO ROOM (Name, ROOM_NUMBER, BED_INFO) VALUES ('Cardinal', '402','kHALI');
INSERT INTO ROOM (Name, ROOM_NUMBER, BED_INFO) VALUES ('Cardinal', '404','kHALI');
INSERT INTO ROOM (Name, ROOM_NUMBER, BED_INFO) VALUES ('DOG', '403','bHARA');
INSERT INTO ROOM (Name, ROOM_NUMBER, BED_INFO) VALUES ('Cardinal', '408','BHARA');